modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="nightmare_mod"
version="1.0.0"
displayName="Nightmare Mod By MCGooglesss"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Manta, MCreator"

[[dependencies.nightmare_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




